# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created: Wed Jun  7 20:42:48 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1041, 667)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.playPAUWidget = QtGui.QTabWidget(self.centralwidget)
        self.playPAUWidget.setObjectName(_fromUtf8("playPAUWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.saveButton = QtGui.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/save.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.resetButton = QtGui.QPushButton(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/reset.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon1)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.neutralButton = QtGui.QPushButton(self.frame)
        self.neutralButton.setObjectName(_fromUtf8("neutralButton"))
        self.horizontalLayout_2.addWidget(self.neutralButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.enableConfigMotorsCheckBox = QtGui.QCheckBox(self.frame)
        self.enableConfigMotorsCheckBox.setObjectName(_fromUtf8("enableConfigMotorsCheckBox"))
        self.horizontalLayout_2.addWidget(self.enableConfigMotorsCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.motorConfigTableWidget = QtGui.QTableWidget(self.frame)
        self.motorConfigTableWidget.setLineWidth(0)
        self.motorConfigTableWidget.setAlternatingRowColors(True)
        self.motorConfigTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.motorConfigTableWidget.setShowGrid(True)
        self.motorConfigTableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.motorConfigTableWidget.setObjectName(_fromUtf8("motorConfigTableWidget"))
        self.motorConfigTableWidget.setColumnCount(0)
        self.motorConfigTableWidget.setRowCount(0)
        self.motorConfigTableWidget.horizontalHeader().setVisible(False)
        self.motorConfigTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.motorConfigTableWidget)
        self.verticalLayout_7.addWidget(self.frame)
        self.playPAUWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loadFrameButton = QtGui.QPushButton(self.tab_2)
        self.loadFrameButton.setObjectName(_fromUtf8("loadFrameButton"))
        self.horizontalLayout.addWidget(self.loadFrameButton)
        self.frameSlider = QtGui.QSlider(self.tab_2)
        self.frameSlider.setEnabled(False)
        self.frameSlider.setPageStep(1)
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName(_fromUtf8("frameSlider"))
        self.horizontalLayout.addWidget(self.frameSlider)
        self.frameSpinBox = QtGui.QSpinBox(self.tab_2)
        self.frameSpinBox.setObjectName(_fromUtf8("frameSpinBox"))
        self.horizontalLayout.addWidget(self.frameSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.splitter_2 = QtGui.QSplitter(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frame_2 = QtGui.QFrame(self.splitter_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.pauValueTableWidget = QtGui.QTableWidget(self.frame_2)
        self.pauValueTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.pauValueTableWidget.setAlternatingRowColors(True)
        self.pauValueTableWidget.setObjectName(_fromUtf8("pauValueTableWidget"))
        self.pauValueTableWidget.setColumnCount(2)
        self.pauValueTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.pauValueTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pauValueTableWidget.setHorizontalHeaderItem(1, item)
        self.pauValueTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.pauValueTableWidget)
        self.tabWidget = QtGui.QTabWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.defaultMapperButton = QtGui.QPushButton(self.tab_3)
        self.defaultMapperButton.setCheckable(True)
        self.defaultMapperButton.setChecked(True)
        self.defaultMapperButton.setObjectName(_fromUtf8("defaultMapperButton"))
        self.horizontalLayout_6.addWidget(self.defaultMapperButton)
        self.trainedMapperButton = QtGui.QPushButton(self.tab_3)
        self.trainedMapperButton.setCheckable(True)
        self.trainedMapperButton.setObjectName(_fromUtf8("trainedMapperButton"))
        self.horizontalLayout_6.addWidget(self.trainedMapperButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.saveMotorValuesButton = QtGui.QPushButton(self.tab_3)
        self.saveMotorValuesButton.setObjectName(_fromUtf8("saveMotorValuesButton"))
        self.horizontalLayout_6.addWidget(self.saveMotorValuesButton)
        self.trainButton = QtGui.QPushButton(self.tab_3)
        self.trainButton.setObjectName(_fromUtf8("trainButton"))
        self.horizontalLayout_6.addWidget(self.trainButton)
        self.enablePlayMotorsCheckBox = QtGui.QCheckBox(self.tab_3)
        self.enablePlayMotorsCheckBox.setObjectName(_fromUtf8("enablePlayMotorsCheckBox"))
        self.horizontalLayout_6.addWidget(self.enablePlayMotorsCheckBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.motorValueTableWidget = QtGui.QTableWidget(self.tab_3)
        self.motorValueTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.motorValueTableWidget.setAlternatingRowColors(True)
        self.motorValueTableWidget.setObjectName(_fromUtf8("motorValueTableWidget"))
        self.motorValueTableWidget.setColumnCount(3)
        self.motorValueTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.motorValueTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.motorValueTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.motorValueTableWidget.setHorizontalHeaderItem(2, item)
        self.motorValueTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.motorValueTableWidget.horizontalHeader().setStretchLastSection(True)
        self.motorValueTableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.motorValueTableWidget)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.enableCalibMotorsCheckBox = QtGui.QCheckBox(self.tab_4)
        self.enableCalibMotorsCheckBox.setObjectName(_fromUtf8("enableCalibMotorsCheckBox"))
        self.horizontalLayout_5.addWidget(self.enableCalibMotorsCheckBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.motorValueCalibTableWidget = QtGui.QTableWidget(self.tab_4)
        self.motorValueCalibTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.motorValueCalibTableWidget.setAlternatingRowColors(True)
        self.motorValueCalibTableWidget.setObjectName(_fromUtf8("motorValueCalibTableWidget"))
        self.motorValueCalibTableWidget.setColumnCount(3)
        self.motorValueCalibTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.motorValueCalibTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.motorValueCalibTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.motorValueCalibTableWidget.setHorizontalHeaderItem(2, item)
        self.motorValueCalibTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_8.addWidget(self.motorValueCalibTableWidget)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_9.addWidget(self.splitter_2)
        self.playPAUWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_3 = QtGui.QSplitter(self.tab_5)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.pauTableWidget = QtGui.QTableWidget(self.splitter_3)
        self.pauTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.pauTableWidget.setAlternatingRowColors(True)
        self.pauTableWidget.setObjectName(_fromUtf8("pauTableWidget"))
        self.pauTableWidget.setColumnCount(2)
        self.pauTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.pauTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pauTableWidget.setHorizontalHeaderItem(1, item)
        self.pauTableWidget.horizontalHeader().setStretchLastSection(True)
        self.motorTableWidget = QtGui.QTableWidget(self.splitter_3)
        self.motorTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.motorTableWidget.setAlternatingRowColors(True)
        self.motorTableWidget.setObjectName(_fromUtf8("motorTableWidget"))
        self.motorTableWidget.setColumnCount(2)
        self.motorTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.motorTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.motorTableWidget.setHorizontalHeaderItem(1, item)
        self.motorTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.splitter_3)
        self.playPAUWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.playPAUWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.treeView = QtGui.QTreeView(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_3.addWidget(self.treeView)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionExit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/quit.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionEditMotors = QtGui.QAction(MainWindow)
        self.actionEditMotors.setObjectName(_fromUtf8("actionEditMotors"))
        self.actionSave_Motor_Settings = QtGui.QAction(MainWindow)
        self.actionSave_Motor_Settings.setIcon(icon)
        self.actionSave_Motor_Settings.setObjectName(_fromUtf8("actionSave_Motor_Settings"))
        self.actionLoad_Motor_Settings = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/open.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Motor_Settings.setIcon(icon3)
        self.actionLoad_Motor_Settings.setObjectName(_fromUtf8("actionLoad_Motor_Settings"))
        self.toolBar.addAction(self.actionLoad_Motor_Settings)
        self.toolBar.addAction(self.actionSave_Motor_Settings)
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.playPAUWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.frameSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.frameSpinBox.setValue)
        QtCore.QObject.connect(self.frameSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.frameSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ServoController", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.neutralButton.setText(_translate("MainWindow", "Neutral", None))
        self.enableConfigMotorsCheckBox.setText(_translate("MainWindow", "Enable Motors", None))
        self.motorConfigTableWidget.setSortingEnabled(True)
        self.playPAUWidget.setTabText(self.playPAUWidget.indexOf(self.tab), _translate("MainWindow", "Config", None))
        self.loadFrameButton.setText(_translate("MainWindow", "Load Frames", None))
        self.label.setText(_translate("MainWindow", "PAU", None))
        item = self.pauValueTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Key", None))
        item = self.pauValueTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        self.defaultMapperButton.setText(_translate("MainWindow", "Default Mapper", None))
        self.trainedMapperButton.setText(_translate("MainWindow", "Trained Mapper", None))
        self.saveMotorValuesButton.setText(_translate("MainWindow", "Save Motor Values", None))
        self.trainButton.setText(_translate("MainWindow", "Train", None))
        self.enablePlayMotorsCheckBox.setText(_translate("MainWindow", "Enable Motors", None))
        item = self.motorValueTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Motor Name", None))
        item = self.motorValueTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        item = self.motorValueTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Editor", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Play", None))
        self.enableCalibMotorsCheckBox.setText(_translate("MainWindow", "Enable Motors", None))
        item = self.motorValueCalibTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Motor Name", None))
        item = self.motorValueCalibTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        item = self.motorValueCalibTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Editor", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Calibration", None))
        self.playPAUWidget.setTabText(self.playPAUWidget.indexOf(self.tab_2), _translate("MainWindow", "Play PAU", None))
        item = self.pauTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Key", None))
        item = self.pauTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        item = self.motorTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Motor Name", None))
        item = self.motorTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        self.playPAUWidget.setTabText(self.playPAUWidget.indexOf(self.tab_5), _translate("MainWindow", "Monitor", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionEditMotors.setText(_translate("MainWindow", "Edit Motors", None))
        self.actionEditMotors.setToolTip(_translate("MainWindow", "Edit Motors", None))
        self.actionSave_Motor_Settings.setText(_translate("MainWindow", "Save Motor Settings", None))
        self.actionLoad_Motor_Settings.setText(_translate("MainWindow", "Load Motor Settings", None))

import res_rc
